LearnTeachCode/code-coffee-compendium

- README.adoc
#4 observed strict usage of 'self-guided'
> closing #4

- README.adoc
> adding focus section for Ruby on Rails, requested by @sugarsyntax

- .gitignore
- README.adoc
Appended '*' to .gitignore extension for .sqlite, as sometimes the extension is written as .sqlite3.
Added an interactive PostgreSQL tutorial from Chartio.
Added a Django reference tutorial from Django Girls.
> added Django Girls and PostgreSQL tutorials

- README.adoc
Replaced "UI" & "Offline" with "Prerequisites" column.
> Closes #19

- README.adoc
- rename "Interactive tutorials" as "Interactive Lessons & Challenges"
- divide table into "Learn a Tech Stack" & "Capture the flag (CTF)"
> KonMari the interactive table

- LICENSE
- README.adoc
- update repo name in README & LICENSE
- update year in LICENSE's copyright claim
> Update repo name

- README.adoc
- add new subheader, Command-Line Utilities
- add cookiecutter w/ description
> add project templates w/ cookiecutter

- README.adoc
> Added online resources

- README.adoc
Fixes the TOC position in AsciiDoc file.
> Move TOC on the left

- README.adoc
New math(linear algebra, stats and prob), web dev(flask framework), and python resources. All are open source and free.
> New math and flask and python resources

- .github/CODEOWNERS
- .github/workflows/docs.yml
add github workflow on merge to master, will kick off build of asciidoctor
relates to #43 
will also create pull request
unrelated:
adding codeowners, to update branch protections so as to require code review from codeowners
> ci: add github workflow/docs.yaml

- convert.rb
Resolving issue #60 
Sitemap was being generated while the site was being indexed, resulting in an error. Thanks @cynful for helping me find a solution for this!
> Generate sitemap _after_ all pages have been indexed

- content/home.adoc
I added a Discord link and a new sentence urging community members to contribute to this site. 
Closes #64
> Add Discord link

- build.sh
- index.html
PR is a temporary patch for #65.
Tested on:
https://github.com/capsulecorplab/code-coffee-compendium/runs/1499855201?check_suite_focus=true
Results on:
https://capsulecorplab.github.io/code-coffee-compendium/ 
closes #65
> add patch for redirecting site to home/

- content/how-to/index0.adoc
Noticed Error in one of the pages showing programming languages. Updated Swift logo
> Added new picture of Swift Logo

- LICENSE
> restore LICENSE

- content/how-to/index.adoc
- content/tutorials/index.adoc
> Good first issue/move automate boring stuff to tutorials/85

- .github/workflows/deploy.yml
> update gh-actions to trigger on main branch

- content/home.adoc
add GitHub link to introduction.
I think I did it right this time.  I added the GitHub link to home.adoc.
> add GitHub link to introduction

- content/references/index.adoc
> Add a guide to pair programming

- .gitmodules
- netlify-build.sh
> Add Dockerfile through submodule
